### ISSUE TITLE
Running ace commands in a controller

### ISSUE THREAD

**Issue by Geowan** [adonisjs/core#1204]
In laravel you can call artisan commands via
     
          Artisan::call('email:send', [
           'user' => 1, '--queue' => 'default'
          ]);

So how can we achieve this in adonis controller.
I have tried this
 
      const { Command } = use('@adonisjs/ace');
      class ConfigurationController {

        //here run ace commands
        async runConfigurations(){
           Command.run("adonis migration:run"); //this doenst work
        }
     }

How can we run ace commands from the controller.

**Comment by RomainLanz** [comment]
Hey @Geowan! 👋 

You need to require ace to run the command.

```js
const ace = require('@adonisjs/ace')

class ConfigurationController {
  runConfigurations () {
    ace.run('migration:run')
  }
}
```

Also, this is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) next time for this kind of request.

**Comment by Geowan** [comment]
HI RomainLanz

After trying this am getting an error ace.run is not a function.

**Comment by RomainLanz** [comment]
Oops, it should be `ace.call()`.

**Comment by Geowan** [comment]
HI after using this as 

      const ace = require('@adonisjs/ace')

      class ConfigurationController {
        runConfigurations () {
          ace.call('migration:run')
        }
    }

This throws an error  migration:run is not a registered command.
When i check on the terminal via `node ace` there is migration:run command

Further checking via
           console.log("commands have ", ace.commands)

Doesn't contain the migration commands. How can i load the migration commands

**Comment by Geowan** [comment]
A quick check on start/app.js found there is `@adonisjs/lucid/providers/MigrationsProvider` in the aceProviders which i believe is the one responsible for the ace migrations commands. But even with it included still it doesnt load migration commands on the controller but migration commands are available on the terminal (console) commands.

**Comment by maxsimych** [comment]
@Geowan is this issue was solved?

**Comment by Geowan** [comment]
@maxsimych  no it wasn't resolved. I ended up writing custom functions to create the tables with knex create table commands which is duplication of what ace migrations does,

**Comment by thetutlage** [comment]
I am not looking to allow to run ace commands from the HTTP server process as of now. It requires some proper thinking and time and will look into it later sometime.

**Comment by Agilulfo1820** [comment]
@thetutlage Can I ask if there is a way to run a command from inside a Task (with adonis-scheduler)?

**Comment by acidiney** [comment]
I have the same problem, I solved using node `child_process`... Is not most beautiful, but can help.
```js

const Helpers = use('Helpers');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

class MockController {
  async run ({ response }) {
    await exec(`cd ${Helpers.appRoot()} && node ace <command>`);

    return response.json({ message: 'ok' })
  }
}


```

**Comment by 852Kerfunkle** [comment]
I have an electron application using Adonis.js and I would like to run migrations on the database on startup. Tried a few things but in the end the app terminates when the migration was run.

Any hints how that could be achieved in code?

**Comment by bartosjiri** [comment]
@852Kerfunkle Not sure if this is applicable for your use case, but you can run you migrations inside the NPM script, similar the following:

1. Edit the `package.json` file:
    ```
    {
      # ...
      "scripts": {
        "build": "node ace migration:run && node ace build --production",
        "start": "node ./build/server.js",
        "dev": "node ace migration:run && node ace serve --watch",
      },
      # ...
    }
    ```
2. Run the relevant command(s):
    ```
    npm run dev
    ```
    or
    ```
    npm run build
    npm run start
    ```

**Comment by 852Kerfunkle** [comment]
@bartosjiri Unfortunately doesn't apply, npm is not available inside electron. But thank you!

**Comment by 852Kerfunkle** [comment]
For anyone looking for the answer, this was added in the 2021 June update: https://docs.adonisjs.com/releases/june-2021-release#run-migrations-programmatically

Make sure you update to @latest

**Comment by JuniorRibas** [comment]
@852Kerfunkle  

Hey, how's it going?

how did you run the migrations using electron?

**Comment by 852Kerfunkle** [comment]
@JuniorRibas 

Hey, see the previous comment (https://github.com/adonisjs/core/issues/1204#issuecomment-887061696).

Or, have a look at: https://docs.adonisjs.com/guides/database/migrations#running-migrations-programmatically

**Comment by jsdecena** [comment]
Update in 2023 for AdonisJs5 https://docs.adonisjs.com/guides/ace-commandline#executing-commands-programmatically

**Comment by CourteousCoder** [comment]
@jsdecena
> Update in 2023 for AdonisJs5 https://docs.adonisjs.com/guides/ace-commandline#executing-commands-programmatically

Thank you for this! I'm using typescript and ES module syntax (`import`/`from`) instead of `require()`. 

### Update in 2025:

Here's the documentation for running ace commands programmatically in [Adonis version 6](https://docs.adonisjs.com/guides/ace/introduction#running-commands-programmatically) 

And here's the latest [web archive permalink](https://web.archive.org/web/20250627222958/https://docs.adonisjs.com/guides/ace/introduction#running-commands-programmatically) of that documentation as of this writing.
